# Site settings
title:          Nemo's blog
description:    "Jeeyun Lee's blog"
url:            "https://jy617lee.github.io"

# Author
author:
  name:         Jeeyun Lee
  url:          https://jy617lee.github.io/
  email:        jy617.lee@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
    - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
remote_theme: chesterhow/tale
theme:      tale

permalink:  /:year-:month-:day/:title
paginate:   5
